### ISSUE TITLE
Tags for Elements (Categories)

### ISSUE THREAD

**Issue by ToTheMoon1234** [OffRange/KeyGo#17]
**Description:**
Every element can be assigned a category like e-mails, e-shoping, bank, credit card etc and all categories and be viewed in one page and that page can be set as the default when opening the app. 

**Problem/Use Case:**
Easier to find passwords and better management 

**Proposed Solution:**
all categories and be viewed in one page and that page can be set as the default when opening the app.

**Comment by OffRange** [comment]
I will name that a "Tag" a user can create and assign to an element.
