### ISSUE TITLE
Support for American Express Card Infirmation Format

### ISSUE THREAD

**Issue by moriel5** [OffRange/KeyGo#24]
Just a heads up, that American Express uses 15-digit card numbers and 4-digit CVV numbers.

Currently both are unsupported by KeyGo.

**Comment by OffRange** [comment]
Exciting news! I'm thrilled to announce that the upcoming update will bring support for multiple card number formats, enhancing versatility and user convenience. I'm eager to roll this out and would love to hear your feedback, perhaps even on Google Play! Your input is invaluable in continually improving the app.
